name: gando
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.2.1
  provider: ^6.0.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  flutter_smart_dialog: ^4.7.1
  pinput: ^2.2.16
  lottie: ^1.0.1
  flutter_snake_navigationbar: ^0.6.1
  text_form_field_wrapper: ^1.0.0
  linear_step_indicator: ^1.0.0+3
  expandable_text: ^2.3.0
  csc_picker: ^0.2.6
  datepicker_dropdown: ^0.0.7+2
  date_ranger: ^0.0.2
  dropdown_button2: ^1.9.2
  multi_select_flutter: ^4.1.3
  syncfusion_flutter_datepicker: ^20.3.61
  flutter_map_marker_cluster: ^1.0.1
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  scrollable_positioned_list: ^0.3.5
  syncfusion_flutter_sliders: ^20.4.41
  syncfusion_flutter_gauges: ^20.4.41
  signature: ^5.3.0
  firebase_core: ^2.4.1
  http: ^0.13.5
  dio: ^4.0.6
  google_sign_in: ^5.4.4
  flutter_onboarding_slider: ^1.0.8
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  sign_in_with_apple: ^4.3.0
  flutter_chat_ui: ^1.6.6
  image_picker: ^0.8.6+3
  permission_handler: ^10.2.0
  image_cropper: ^3.0.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  # The "flutter_lints" package below contains-analysis options that
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_G.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/lotties/
    - assets/lotties/zip/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
