// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxED3f7nFBWfWjmuTz7dkuudWMM787TqE',
    appId: '1:260961065510:web:af0b69f628baf5f1e024e7',
    messagingSenderId: '260961065510',
    projectId: 'gando-app',
    authDomain: 'gando-app.firebaseapp.com',
    storageBucket: 'gando-app.appspot.com',
    measurementId: 'G-70B9V3CEWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxDOU_vbVlgshwo1nVowz0Sd_ZsVSoU0',
    appId: '1:260961065510:android:ce83c6ba7e3e185ae024e7',
    messagingSenderId: '260961065510',
    projectId: 'gando-app',
    storageBucket: 'gando-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONHjvgZJS_dvJjfZdf5IOvlgrS-Qjhc8',
    appId: '1:260961065510:ios:aa2eaa9c15df0294e024e7',
    messagingSenderId: '260961065510',
    projectId: 'gando-app',
    storageBucket: 'gando-app.appspot.com',
    androidClientId: '260961065510-et40phdeclo0c0ks4q68q49m8io561re.apps.googleusercontent.com',
    iosClientId: '260961065510-gd0jkq24u00bl99ovkfmnq013tg4a394.apps.googleusercontent.com',
    iosBundleId: 'com.gando.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCONHjvgZJS_dvJjfZdf5IOvlgrS-Qjhc8',
    appId: '1:260961065510:ios:74ddee2a65026fb6e024e7',
    messagingSenderId: '260961065510',
    projectId: 'gando-app',
    storageBucket: 'gando-app.appspot.com',
    androidClientId: '260961065510-et40phdeclo0c0ks4q68q49m8io561re.apps.googleusercontent.com',
    iosClientId: '260961065510-9etvnglcq20mcdt8csclgt15a3v7ugbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gando',
  );
}
